#! /bin/bash

. ./lib

# option 1: export and import
get_db awp_b --lock-tables=false
set_user_db awp awp_b

# option 2: copy table files, this leads to the mysql table "in use" problem
if [ 0 = 1 ]; then
	if [ -d "$mysql_datadir/awp_b" ]; then
		ml_echo "database awp_b is existing"
	else
		awp_b_rdir="C:\\Documents and Settings\\All Users\\Application Data\\MySQL\\MySQL Server 5.1\\Data\\awp_b"
		sql="CREATE DATABASE awp_b DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci"
		$lcmysql -uroot -p$lcmysqlpw -e "$sql"
		ls -all $mysql_datadir/awp_b
		rget "$awp_b_rdir" "$mysql_datadir" "extract"
		ls -all $mysql_datadir/awp_b/db.opt
		set_db_user awp WK4SvY6fRjFYbRAc
		set_user_db awp awp_b
	fi
	chmod -R 0660 "$mysql_datadir/awp_b"
fi

get_table awp textdata
